name: Development Checks

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  quick-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn[standard] pydantic-settings python-dotenv
        pip install pytest flake8
        
    - name: Quick lint check
      working-directory: ./backend
      run: |
        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Import test
      working-directory: ./backend
      run: |
        python -c "from app.main import app; print('✅ FastAPI app imports successfully')"
        
    - name: Quick tests
      working-directory: ./backend
      env:
        PYTHONPATH: /home/runner/work/GoGoTrade/GoGoTrade/backend
      run: |
        python -m pytest ../tests/ -v --tb=short
